// <auto-generated />
using System;
using MAS_projekt_s22580.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAS_projekt_s22580.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240616172858_Initt")]
    partial class Initt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MAS_projekt_s22580.Models.Clients.BasicClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("BasicClient");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Clients.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("PhoneNumber");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Number = "123-456-789"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            Number = "098-765-432"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 2,
                            Number = "111-111-111"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 3,
                            Number = "222-222-222"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 4,
                            Number = "987-654-321"
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 4,
                            Number = "555-555-555"
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmploymentDate = new DateTime(2024, 6, 6, 19, 28, 58, 521, DateTimeKind.Local).AddTicks(2138),
                            PersonId = 1,
                            Salary = 4500.0,
                            SellerId = 0,
                            SpecialistId = 0
                        },
                        new
                        {
                            Id = 2,
                            EmploymentDate = new DateTime(2023, 2, 16, 19, 28, 58, 521, DateTimeKind.Local).AddTicks(2196),
                            PersonId = 2,
                            Salary = 5000.0,
                            SellerId = 0,
                            SpecialistId = 0
                        },
                        new
                        {
                            Id = 3,
                            EmploymentDate = new DateTime(2023, 2, 2, 19, 28, 58, 521, DateTimeKind.Local).AddTicks(2202),
                            PersonId = 3,
                            Salary = 5500.0,
                            SellerId = 0,
                            SpecialistId = 0
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Employees.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("KnowledgeLevel")
                        .HasColumnType("int");

                    b.Property<int>("SalesTarget")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Seller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            KnowledgeLevel = 3,
                            SalesTarget = 100
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 3,
                            KnowledgeLevel = 9,
                            SalesTarget = 200
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Employees.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Specialist");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            EmployeeId = 1,
                            Specialization = "Electric guitars",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 2,
                            Specialization = "Acoustic guitars",
                            YearsOfExperience = 6
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Guitars.GuitarExemplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGuitarType")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdGuitarType");

                    b.HasIndex("IdOrder");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("GuitarExemplars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdGuitarType = 1,
                            IdOrder = 1,
                            SerialNumber = "SN1234"
                        },
                        new
                        {
                            Id = 2,
                            IdGuitarType = 2,
                            IdOrder = 2,
                            SerialNumber = "SN6789"
                        },
                        new
                        {
                            Id = 3,
                            IdGuitarType = 3,
                            IdOrder = 3,
                            SerialNumber = "SN9238"
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Guitars.GuitarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyMaterial")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FretboardMaterial")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("NumberOfStrings")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GuitarTypes", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("GuitarType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientID = 1,
                            EmployeeID = 1,
                            OrderNumber = "A1234",
                            Status = "Submitted"
                        },
                        new
                        {
                            Id = 2,
                            ClientID = 2,
                            EmployeeID = 2,
                            OrderNumber = "B9876",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            ClientID = 3,
                            EmployeeID = 1,
                            OrderNumber = "C1928",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            ClientID = 2,
                            EmployeeID = 2,
                            OrderNumber = "D5678",
                            Status = "Received"
                        },
                        new
                        {
                            Id = 5,
                            ClientID = 4,
                            EmployeeID = 1,
                            OrderNumber = "E9876",
                            Status = "Canceled"
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 0,
                            EmployeeId = 0,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 0,
                            EmployeeId = 0,
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 0,
                            EmployeeId = 0,
                            FirstName = "Michael",
                            LastName = "Collins"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 0,
                            EmployeeId = 0,
                            FirstName = "Monica",
                            LastName = "Williams"
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Clients.ClientStandard", b =>
                {
                    b.HasBaseType("MAS_projekt_s22580.Models.Clients.BasicClient");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ClientStandard");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "jane.smith@example.com",
                            PersonId = 2,
                            LoyaltyPoints = 150
                        },
                        new
                        {
                            Id = 4,
                            Email = "monica.williams@example.com",
                            PersonId = 4,
                            LoyaltyPoints = 125
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Clients.ClientVip", b =>
                {
                    b.HasBaseType("MAS_projekt_s22580.Models.Clients.BasicClient");

                    b.Property<int>("VipMembershipLevel")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ClientVip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@email.com",
                            PersonId = 1,
                            VipMembershipLevel = 3
                        },
                        new
                        {
                            Id = 2,
                            Email = "michael.collins@email.com",
                            PersonId = 3,
                            VipMembershipLevel = 10
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Guitars.AcousticGuitar", b =>
                {
                    b.HasBaseType("MAS_projekt_s22580.Models.Guitars.GuitarType");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AcousticGuitar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyMaterial = "Spruce",
                            Brand = "Yamaha",
                            FretboardMaterial = "Rosewood",
                            Model = "F310",
                            NumberOfStrings = 6,
                            Price = 150.0,
                            BodyType = "Dreadnought"
                        },
                        new
                        {
                            Id = 2,
                            BodyMaterial = "Cedar",
                            Brand = "Taylor",
                            FretboardMaterial = "Ebony",
                            Model = "214ce",
                            NumberOfStrings = 6,
                            Price = 1000.0,
                            BodyType = "Grand Auditorium"
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Guitars.BassGuitar", b =>
                {
                    b.HasBaseType("MAS_projekt_s22580.Models.Guitars.GuitarType");

                    b.Property<string>("BridgeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfFrets")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("BassGuitar");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            BodyMaterial = "Alder",
                            Brand = "Fender",
                            FretboardMaterial = "Maple",
                            Model = "Jazz Bass",
                            NumberOfStrings = 4,
                            Price = 1200.0,
                            BridgeType = "Fixed",
                            NumberOfFrets = 20
                        },
                        new
                        {
                            Id = 4,
                            BodyMaterial = "Mahogany",
                            Brand = "Ibanez",
                            FretboardMaterial = "Rosewood",
                            Model = "SR505",
                            NumberOfStrings = 5,
                            Price = 900.0,
                            BridgeType = "Fixed",
                            NumberOfFrets = 24
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Guitars.ElectricGuitar", b =>
                {
                    b.HasBaseType("MAS_projekt_s22580.Models.Guitars.GuitarType");

                    b.Property<string>("PickupsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ElectricGuitar");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            BodyMaterial = "Alder",
                            Brand = "Fender",
                            FretboardMaterial = "Maple",
                            Model = "Stratocaster",
                            NumberOfStrings = 6,
                            Price = 1500.0,
                            PickupsType = "Single Coil"
                        },
                        new
                        {
                            Id = 6,
                            BodyMaterial = "Mahogany",
                            Brand = "Gibson",
                            FretboardMaterial = "Rosewood",
                            Model = "Les Paul",
                            NumberOfStrings = 6,
                            Price = 2500.0,
                            PickupsType = "Humbucker"
                        });
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Clients.BasicClient", b =>
                {
                    b.HasOne("MAS_projekt_s22580.Models.Person", "Person")
                        .WithOne("Client")
                        .HasForeignKey("MAS_projekt_s22580.Models.Clients.BasicClient", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Clients.PhoneNumber", b =>
                {
                    b.HasOne("MAS_projekt_s22580.Models.Clients.BasicClient", "Client")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Employees.Employee", b =>
                {
                    b.HasOne("MAS_projekt_s22580.Models.Person", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("MAS_projekt_s22580.Models.Employees.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Employees.Seller", b =>
                {
                    b.HasOne("MAS_projekt_s22580.Models.Employees.Employee", "Employee")
                        .WithOne("Seller")
                        .HasForeignKey("MAS_projekt_s22580.Models.Employees.Seller", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Employees.Specialist", b =>
                {
                    b.HasOne("MAS_projekt_s22580.Models.Employees.Employee", "Employee")
                        .WithOne("Specialist")
                        .HasForeignKey("MAS_projekt_s22580.Models.Employees.Specialist", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Guitars.GuitarExemplar", b =>
                {
                    b.HasOne("MAS_projekt_s22580.Models.Guitars.GuitarType", "Type")
                        .WithMany("GuitarExemplars")
                        .HasForeignKey("IdGuitarType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MAS_projekt_s22580.Models.Order", "Order")
                        .WithMany("Guitars")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Order", b =>
                {
                    b.HasOne("MAS_projekt_s22580.Models.Clients.BasicClient", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAS_projekt_s22580.Models.Employees.Seller", "Seller")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Clients.BasicClient", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Employees.Employee", b =>
                {
                    b.Navigation("Seller")
                        .IsRequired();

                    b.Navigation("Specialist")
                        .IsRequired();
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Employees.Seller", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Guitars.GuitarType", b =>
                {
                    b.Navigation("GuitarExemplars");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Order", b =>
                {
                    b.Navigation("Guitars");
                });

            modelBuilder.Entity("MAS_projekt_s22580.Models.Person", b =>
                {
                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("Employee")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
